spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/onlypets
    username: onlypets
    password: onlypets

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format-sql: true
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
        registration:
          discord:
            provider: discord
            redirect-uri: http://localhost:8080/oauth2/callback
            authorization-grant-type: authorization_code
            scope: identify
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}